# Generated by Django 3.0.2 on 2020-01-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('task', 'task'), ('todo', 'todo')], default='task', max_length=5),
        ),
    ]
